import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@site-haus/ui/components/base/sidebar";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { AppSideBar } from "./components/sidebar/app-sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "SiteHaus - Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en">
      <body>
        <SidebarProvider defaultOpen={defaultOpen}>
          <AppSideBar />
          <SidebarInset>
            <main>
              <SidebarTrigger className="ml-2 mt-2" />
              <div>{children}</div>
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
