import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@site-haus/ui/components/base/sidebar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import { AppSideBar } from "./components/app-sidebar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "SiteHaus - Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en">
      <body>
        <SidebarProvider defaultOpen={defaultOpen}>
          <AppSideBar />
          <SidebarInset>
            <main>
              <SidebarTrigger className="ml-2 mt-2" />
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
