services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args: { APP_NAME: web }
    restart: always
    networks:
      - sitehaus-network

  dashboard:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
      args: { APP_NAME: dashboard }
    restart: always
    networks:
      - sitehaus-network

  iam:
    build:
      context: .
      dockerfile: ./apps/iam/Dockerfile
      args: { APP_NAME: iam }
    restart: always
    networks:
      - sitehaus-network

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args: { APP_NAME: api }
    restart: always
    env_file:
      - ./apps/api/.env
    networks:
      - sitehaus-network

  caddy:
    image: caddy:2.10.0-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - sitehaus-network
    env_file:
      - .env
    depends_on:
      - web
      - dashboard
      - iam

networks:
  sitehaus-network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
