services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    networks:
      - sitehaus-network

  dashboard:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    restart: always
    networks:
      - sitehaus-network

  caddy:
    image: caddy:2.10.0-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - sitehaus-network
    env_file:
      - .env
    depends_on:
      - web
      - dashboard

networks:
  sitehaus-network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
