services:
  web:
    image: ghcr.io/sitehaus/sitehaus-web:latest
    restart: always
    networks:
      - sitehaus-network

  dashboard:
    image: ghcr.io/sitehaus/sitehaus-dashboard:latest
    restart: always
    networks:
      - sitehaus-network

  iam:
    image: ghcr.io/sitehaus/sitehaus-iam:latest
    restart: always
    networks:
      - sitehaus-network

  api:
    image: ghcr.io/sitehaus/sitehaus-api:latest
    restart: always
    env_file:
      - ./apps/api/.env
    networks:
      - sitehaus-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - sitehaus-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2.10.0-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - sitehaus-network
    env_file:
      - .env
    depends_on:
      - web
      - dashboard
      - iam
      - api

networks:
  sitehaus-network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  redis_data:
    driver: local
