services:
  db:
    image: "postgres:17"
    container_name: sitehaus-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sitehaus-network

volumes:
  postgres_data:
    driver: local

networks:
  sitehaus-network:
    driver: local
