import { ThemeProvider } from "@site-haus/ui/components/base/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { SiteNav } from "./components/SiteNav";
import "./globals.css";

const funnelDisplay = localFont({
  src: "./fonts/FunnelDisplay[wght].woff2",
  variable: "--font-display",
  display: "swap",
});

const commumSans = localFont({
  src: "./fonts/ComumSans-Regular.otf",
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${funnelDisplay.variable} ${commumSans.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SiteNav />
          {children}
          <footer>{new Date().getFullYear().toString()} © SiteHaus</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
